"""Declarative base and reusable model mixins.

Every ORM model inherits `Base`. Cross-cutting columns (UUID primary key,
timezone-aware created/updated timestamps) live in mixins here instead of
being copy-pasted per model or baked into a single "god" base class that
forces columns onto tables that don't want them.
"""

import uuid
from datetime import datetime

from sqlalchemy import DateTime, func, text
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column


class Base(DeclarativeBase):
    """Shared declarative base for all ORM models. Alembic's `env.py`
    points at `Base.metadata` as the single source of truth for schema
    autogeneration/comparison."""


class UUIDPrimaryKeyMixin:
    """Server-generated UUIDv4 primary key.

    Generated by Postgres itself via `gen_random_uuid()` (built into
    Postgres 13+ core — no `pgcrypto`/`uuid-ossp` extension required)
    rather than in Python. This keeps the ID correct and unique even for
    rows inserted outside the ORM (raw SQL, another service, a data
    migration), which a client-side `default=uuid.uuid4` cannot guarantee.
    """

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        server_default=text("gen_random_uuid()"),
    )


class TimestampMixin:
    """Timezone-aware `created_at`/`updated_at`, both set by the database
    (not the application clock), so clock skew between app instances or
    workers can never produce an `updated_at` earlier than `created_at`."""

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        nullable=False,
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        onupdate=func.now(),
        nullable=False,
    )
