{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: agentabi
  namespace: {{ .Values.namespace }}
  annotations:
    kubernetes.io/ingress.class: gce
{{- with .Values.gcp.staticIpName }}
    kubernetes.io/ingress.global-static-ip-name: {{ . | quote }}
{{- end }}
spec:
  rules:
    - http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: agentabi-api
                port:
                  number: 80
          - path: /
            pathType: Prefix
            backend:
              service:
                name: agentabi-frontend
                port:
                  number: 80
{{- end }}
